version: '3'
services:
  sdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: project
    ports:
      - "3309:3306"
  sapi:
    build: 
      context: ./backend/project/
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
  sweb:
    build: 
      context: ./frontend/app/
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
