version: '3'

services:
  sapi:
    build: 
      context: ./backend/project/
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    networks:
      - snet

  sweb:
    build: 
      context: ./frontend/app/
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - snet

  nginx-file-server:
    image: nginx
    volumes:
      - ./videos:/usr/share/nginx/html:ro
    ports:
      - "8001:80"
    networks:
      - snet

networks:
  snet:
